<a href="https://colab.research.google.com/github/ganesh-deshmukh/google-colab-hcr/blob/master/learning_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [29]:
a = np.array([1,2,3])
print(a)

[1 2 3]
[1 2 3]


In [30]:
m2 = np.matrix(a)
print(m2)

[[1 2 3]]
[[1 2 3]]
